services:
  - type: web
    name: serious-sport-sync
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "7000"
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USER
        value: admin
